package com.example.myfish.model

import com.example.myfish.R

object FishData {
    val fishes = listOf(
        Fish(
            1,
            "Cupang",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-cupang.jpeg",
            R.string.deskripsi_cupang

        ),
        Fish(
            2,
            "Arwana",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-arwana.jpeg\n",
            R.string.deskripsi_arwana
        ),
        Fish(
            3,
            "Koi",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan -koi.jpeg\n",
            R.string.deskripsi_koi
        ),
        Fish(
            4,
            "Guppy",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-guppy.jpeg\n",
            R.string.deskripsi_guppy
        ),
        Fish(
            5,
            "Molly",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-molly.jpeg\n",
            R.string.deskripsi_molly
        ),
        Fish(
            6,
            "Neon Tetra",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-neontetra.jpeg\n",
            R.string.deskripsi_neontetra
        ),
        Fish(
            7,
            "Discus",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-discus.jpeg\n",
            R.string.deskripsi_discus
        ),
        Fish(
            8,
            "Louhan",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-louhan.jpeg\n",
            R.string.deskripsi_louhan
        ),
        Fish(
            9,
            "Oscar",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-oscar.jpeg\n",
            R.string.deskripsi_oscar
        ),
        Fish(
            10,
            "Manfish",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-manfish.jpeg\n",
            R.string.deskripsi_manfish
        ),
        Fish(
            11,
            "Platy",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-platy.jpeg\n",
            R.string.deskripsi_platy
        ),
        Fish(
            12,
            "Swordtail",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-swordtail.jpeg\n",
            R.string.deskripsi_swordtail
        ),
        Fish(
            13,
            "Zebra Danio",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-zebradanio.jpeg\n",
            R.string.deskripsi_zebradanio
        ),
        Fish(
            14,
            "Corydoras",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-corydoras.jpeg\n",
            R.string.deskripsi_corrydoras
        ),
        Fish(
            15,
            "Sapu-Sapu",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-sapusapu.jpeg\n",
            R.string.deskripsi_sapusapu
        ),
        Fish(
            16,
            "Nila",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-nila.jpeg\n",
            R.string.deskripsi_nila
        ),
        Fish(
            17,
            "Lele",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-lele.jpeg\n",
            R.string.deskripsi_lele
        ),
        Fish(
            18,
            "Patin",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-patin.jpeg\n",
            R.string.deskripsi_patin
        ),
        Fish(
            19,
            "Gurame",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-gurame.jpeg\n",
            R.string.deskripsi_gurame
        ),
        Fish(
            20,
            "Mas",
            "https://raw.githubusercontent.com/nrhdyt3012/AssetCompose/main/ikan-mas.jpeg\n",
            R.string.deskripsi_mas
        )
    )
}


